[package]
name = "gcode_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
trycmd = { version = "0.14.6", features = ["examples"] }
